### ISSUE TITLE
DataHarmonizer's linkml-datastructure branch doesn't use our validation rules

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/sheets_and_friends#104]
Validation rules currently come from the [validation_converter](https://docs.google.com/spreadsheets/d/1cMlPKgjZh-v21aMYCm9x1TxzE5BwGQptBQcvuaYAtC8/edit#gid=928747012) sheet and are processed by `sheets_and_friends/converters/linkml2dataharmonizer.py`

That gets bypassed when we use DataHarmonizer's linkml-datastructure branch, which takes our `nmdc_dh.yaml` as input

see also https://github.com/cidgoh/DataHarmonizer/issues/290

**Comment by turbomam** [comment]
“{float} {unit}”

string serialization is interpolation where the things in curly brackets are **slots**

**Comment by turbomam** [comment]
full_name: string_serialization: “{given} {family}”

means that things with a `full_name` must also have a `given` value and a `family`value

**Comment by turbomam** [comment]
structured pattern: intent is to vlidate

**Comment by sujaypatil96** [comment]
On course to make a PR which adds `pattern` property to the slots in the NMDC schema generated from sheets_and_friends.

**Comment by turbomam** [comment]
@sujaypatil96 @ssarrafan I see some good developments for this issue in #115, but I don't think I understand how to use it. I have added some discussion about this to the [dh_testing README](https://github.com/microbiomedata/dh_testing/blob/main/README.md)
