### ISSUE TITLE
compare our double-click help screens

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/sheets_and_friends#106]
stable location for DH from old data.tsv pathway: https://data.microbiomedata.org/submission/samples

new linkml-datastrucutre interface: https://deploy-preview-101--voluble-pika-79eed4.netlify.app/linkml?template=nmdc_dh/soil_emsl_jgi_mg

look for example at the help for the first column, globally unique id (or whatever)

**Comment by pkalita-lbl** [comment]
I think the necessary changes have been merged into the `linkml-datastructure` branch of [cidgoh/DataHarmonizer](https://github.com/cidgoh/DataHarmonizer). Is there anything needed in this repo (updating the DH submodule?) before closing this issue?

**Comment by pkalita-lbl** [comment]
The required DH changes have been pulled into this repo's submodule. Closing
