### ISSUE TITLE
Feedback on new environmental packages in Data Harmonizer

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/sheets_and_friends#112]
This GH issue is to collect feedback on the latest version of the DH at 

https://deploy-preview-101--voluble-pika-79eed4.netlify.app/linkml?template=nmdc_dh/soil_emsl_jgi_mg

**Comment by turbomam** [comment]
The lastest NMDC DataHarmonizer, built using Damion's linkml-datastructure branch, can be found at https://deploy-preview-101--voluble-pika-79eed4.netlify.app/linkml?template=nmdc_dh/soil_emsl_jgi_mg

It can be easily regenerated by running make docs/template/nmdc_dh/schema.js in the  issue-100-netlify-linkml-datastructure branch of sheets_and_friends. See https://github.com/microbiomedata/sheets_and_friends/issues/111

All 12 environmental packages can be accessed via the template button towards the upper left.

The section and column layouts are based on some improved sematics [@Sujay Patil](https://nmdc-group.slack.com/team/U02UENGHECD) put into place recently. For [soil_emsl_jgi_mg](https://deploy-preview-101--voluble-pika-79eed4.netlify.app/linkml?template=nmdc_dh/soil_emsl_jgi_mg), the layout matches the portal.

Some things are incomplete:
- regular expression-based validation
- GOLD paths are soil-centric, no matter which package template you're using
- The MIxS triad columns haven't been populated with hierarchical pulldowns yet, even for soil
- The help screens accessible by double-clicking column headers are not identical to the screens that appear in the portal yet.

**Maybe more. Let us know!**

**Comment by turbomam** [comment]
@ssarrafan what do you think of removing me from the assignees list since this isn't really work for me to do? It's work for others to do, and then report their findings to me.

**Comment by ssarrafan** [comment]
> @ssarrafan what do you think of removing me from the assignees list since this isn't really work for me to do? It's work for others to do, and then report their findings to me.

Sure. Let me check with Pajau and Montana.

**Comment by pvangay** [comment]
checked in a bunch of issues for mark into sheets and friends.

also had some help from 5 beta testers (Champions) this week. still need to turn some of their feedback into issues (@ssarrafan can you create an issue for me for May to do this?) but none were show stoppers for the release so I haven't done this formally yet. Closing this issue for now.

**Comment by ssarrafan** [comment]
> checked in a bunch of issues for mark into sheets and friends.
> 
> also had some help from 5 beta testers (Champions) this week. still need to turn some of their feedback into issues (@ssarrafan can you create an issue for me for May to do this?) but none were show stoppers for the release so I haven't done this formally yet. Closing this issue for now.

Here you go @pvangay:  https://github.com/microbiomedata/NMDC_Planning/issues/213
