### ISSUE TITLE
NMDC Apr release prioritization with Sujay and Patrick K

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/sheets_and_friends#113]
The next NMDC release date is April 22nd. I don't have anything right now to define what that's supposed to include overall

Here's [my NMDC project board for this month](https://github.com/orgs/microbiomedata/projects/22?card_filter_query=assignee%3Aturbomam)

[My DataHarmonizer issues](https://github.com/cidgoh/DataHarmonizer/issues/created_by/turbomam)

[@sujaypatil96's DH issues](https://github.com/cidgoh/DataHarmonizer/issues/created_by/sujaypatil96)

Recent MIxS issues: https://github.com/GenomicsStandardsConsortium/mixs/issues?q=is%253Aopen+is%253Aissue+involves%253Aturbomam

**Comment by sujaypatil96** [comment]
Quick update, 4/14: I am on course to deliver a PR for issue #104. Will update this issue when it's done.
