### ISSUE TITLE
coordinate linkml-datastructure integration with Brandon

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/sheets_and_friends#114]

**Comment by turbomam** [comment]
this is a dupe

**Comment by turbomam** [comment]
@turbomam introduce them!

**Comment by turbomam** [comment]
minify true doesn't seem to be working

https://deploy-preview-101--voluble-pika-79eed4.netlify.app/linkml?minify=true

**Comment by pkalita-lbl** [comment]
The integration happened. I don't think there is anything left to do on this. Closing.

**Comment by turbomam** [comment]
@ssarrafan I trust @pkalita-lbl's decision to close this, but I still need to learn a lot about the new pipeline for building DH interfaces. Will require documentation, but I believe some of it is still in flux.

See the [dh_testing README.md](https://github.com/microbiomedata/dh_testing/blob/1850c7bfd37898897cdc313f245560b5c6e7d086/README.md)
