### ISSUE TITLE
deal with non-string serialization validations

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/sheets_and_friends#116]
like minimums, maximums, data types?

**Comment by sujaypatil96** [comment]
If you look within the linkml-datastructure branch, specifically at this code block: https://github.com/cidgoh/DataHarmonizer/blob/linkml-datastructure/script/main_linkml.js#L975-L1091, you'll see that Damion already has logic within main_linkml.js to handle when it sees schema ranges that we have in our [spreadsheet](https://docs.google.com/spreadsheets/d/1cMlPKgjZh-v21aMYCm9x1TxzE5BwGQptBQcvuaYAtC8/edit?usp=sharing).

**Comment by turbomam** [comment]
great. I think this may related to some other issue. I'll try to link them up later today

**Comment by turbomam** [comment]
@ssarrafan : @sujaypatil96 makes a good point about existing minimum and maximum support in DataHarmonizer. I have an accounting of all of the other slot attributes we provide in sheets_and_friends, and whether they are addressed in DataHarmioizer yet. I'll look at that tomorrow or Thursday.

**Comment by turbomam** [comment]
@ssarrafan I created a repo called [dh_testing](https://github.com/microbiomedata/dh_testing) that makes it easy to test the degree to which DH supports LinkML language features. 

It looks like there is indeed [support for most of the the slots that could reasonably be used](https://github.com/microbiomedata/dh_testing/issues/3#issue-1320224735) for documentation and validation.  In other words, much more than validating against `string_serialization`s. _Actually, what I was calling validation against `string_serialization` is really being handled by pattern and structured_pattern._   

I will be adding issues to [dh_testing](https://github.com/microbiomedata/dh_testing) to document DH support for some LinkML features that
- could be added
- might be broken or better documented
