### ISSUE TITLE
Enable EnvO triad dropdowns for soil package

### ISSUE THREAD

**Issue by pvangay** [microbiomedata/sheets_and_friends#118]
Previously, the soil templates supported dropdowns for the EnvO triad terms. These values were subsets of EnvO that were most appropriate for the environment (soil), and allowed the user to type in and search for terms within the dropdown. Currently, these drop downs are no longer available in the soil templates. Suggestion: enable dropdowns for templates that have subsets available (currently, soil only).

See [this DH link](https://data.dev.microbiomedata.org/submission/49e40955-31c7-44a7-9e31-8499335019e6/samples) for reference (admin privileges required)
![image (6)](https://user-images.githubusercontent.com/7374085/165179499-906661f0-c52f-441e-84be-926d2fd09092.png)

**Comment by mslarae13** [comment]
I recommend this be reassigned to @pkalita-lbl to ensure the drop downs work in the new DH template with the tab view...
thoughts? @turbomam

**Comment by pkalita-lbl** [comment]
This isn't really related to the tab view work. I suspect this is something that needs to be fixed in the process that generates the submission schema.

**Comment by turbomam** [comment]
> I suspect this is something that needs to be fixed in the process that generates the submission schema.

That's mostly true.

We have some curation to support this task in [Sheet sheets-for-nmdc-submission-schema, tab envo_terms_for_mixs_env_triad](https://docs.google.com/spreadsheets/d/1cMlPKgjZh-v21aMYCm9x1TxzE5BwGQptBQcvuaYAtC8/edit#gid=993240342)

the sheets_and_friends Makefile does have a [rule that takes envo_terms_for_mixs_env_triad as input](https://github.com/microbiomedata/sheets_and_friends/blob/d93ce72be9bf96af6316e01dfdd947cb2983d3c0/Makefile#L92-L100), but I really need to revisit what's going on there.

Presumably we want more curated EnvO terms for more environmental packages. I have no idea at this point where I got the content in envo_terms_for_mixs_env_triad.

**Comment by mslarae13** [comment]
environmental triad drop downs are present in soil
Still need drop downs for the other extensions
Need a more automated way of identifying what terms should be used for which MIxS extensions
- ENVO should have something that says 'this is only a soil term' 
Having contextual constrains and a 'tree' like way of building your terms would be helpful. 

I will make tickets and link here

**Comment by mslarae13** [comment]
The soil drop downs work in -dev. Regardless of template / data types.

In -sandbox (likely prod too), the drop downs do NOT work when you have not selected JGI or EMSL, OR when you select any of the OTHER data types.

In -sandbox, the drop downs DO work when you select metaG, metaT, metaP, metaB, NOM, and any combination of ONLY user facility options

@pkalita-lbl , @turbomam , is it safe to say, since these work in -dev, when we push to -prod they will keep working & we can close this ticket?

**Comment by pkalita-lbl** [comment]
> is it safe to say, since these work in -dev, when we push to -prod they will keep working & we can close this ticket?

Yes

**Comment by ssarrafan** [comment]
Closing this issue based on @pkalita-lbl last comment
