### ISSUE TITLE
Elevation should be required in the soil template

### ISSUE THREAD

**Issue by pvangay** [microbiomedata/sheets_and_friends#120]
![image](https://user-images.githubusercontent.com/7374085/165183753-be76cd6f-7763-4d0f-8b4c-c4d828461c32.png)

For reference, [see DH link](https://data.dev.microbiomedata.org/submission/822e290d-6837-4956-abb9-996dd5f6d8b9/samples) - admin privileges required.

Elevation is required in the MIxS soil package ([confirmed in v6](https://genomicsstandardsconsortium.github.io/mixs/Soil/)). During the GSP workshop, we demo'd it as required ([see last page of solutions for attendees](https://docs.google.com/document/d/1nz5v7L_ftZ72YjPSLD89SZGBXtpejITVXhNHfNz1UYY/edit#)). Currently, validation only flags entries with missing units, but does not flag empty cells.

**Comment by turbomam** [comment]
OK, I need to set it's LinkML `required` attribute to `True`

For which environments should it be required? Should I just check with MIxS :-) ?

I'm confused about why it's in the MIxS modified section already... nothing has been modified. I think that section membership is declared in the Google Sheet now instead of being detected by inspection.

**Comment by turbomam** [comment]
Confirming that `elev` is [required](https://github.com/GenomicsStandardsConsortium/mixs/blob/74744eea9b149b0587b58f48e3dd8d1f879820d2/model/schema/soil.yaml#L86-L87) for the soil environmental package within the MIxS LinkML model

**Comment by mslarae13** [comment]
Check sheets and friends elevation is required in modifications long & this slot is required in the submission portal.

**Comment by turbomam** [comment]
I am confirming that `SoilInterface` entries in the new submission schema require `elev` entries now. I will link the files that demonstrate that fact.

**Comment by turbomam** [comment]
https://github.com/microbiomedata/submission-schema/blob/main/src/data/valid/SampleData-soil-data-exhaustive.yaml contains two `SoilInterface`s, captured in the `soil_data` slot.

- source_mat_id: x:1
- source_mat_id: x:2

Both have `elev` values of 123. 

Note the absence of any units. We should ensure that this column is entitled "elevation in meters". @cmungall has some long term solutions so we won't have to manually manage slot names, title and validation rules, esp. with regards to measurements that have explicit or implicit units.

**Comment by turbomam** [comment]
I also created 
- a simpler SampleData-soil-data-minimal.yaml sampel data file
- an invalid src/data/invalid/SampleData-soil-data-missing-elev.yaml, which lacks `elev`. The Makefile expects files in src/data/invalid to be invalid. If there are valid, then the build process fails.

This demonstrates that `elev` is both available and required for `SoilInterface`s

@sujaypatil96 @pkalita-lbl and I can help colleagues create valid and invalid test files like these to check their expectations
