### ISSUE TITLE
Soil sample storage temperature help example fails on validation

### ISSUE THREAD

**Issue by pvangay** [microbiomedata/sheets_and_friends#121]
[For reference, DH interface link](https://data.dev.microbiomedata.org/submission/49e40955-31c7-44a7-9e31-8499335019e6/samples) - admin required.

Using the example provided in the help fails on validation.
![image](https://user-images.githubusercontent.com/7374085/165366727-2912ca55-5737-44fc-bdac-5779a8d2360e.png)

![image](https://user-images.githubusercontent.com/7374085/165366688-b893481f-6775-479f-987b-02bd9876536b.png)

Please either update the help text or the validation rules so that both are consistent with each other.

**Comment by turbomam** [comment]
Hmm, I think I can fix this in [`nmdc-dh-sheets-mam-non-anno` sheet `modifications_long`](https://docs.google.com/spreadsheets/d/1cMlPKgjZh-v21aMYCm9x1TxzE5BwGQptBQcvuaYAtC8/edit#gid=1241218612)

Note to self:
- [ ] Google Sheet needs better name
- [ ] Should probably be made view-only do people don't edit it
- [ ] I need to write documentation on how to edit the Sheet

**Comment by turbomam** [comment]
Back to the issue at hand: 

@pvangay 

my pattern `^[-+]?[0-9]*\.?[0-9]+([eE][-+]?[0-9]+)? \S+$` expects 

- a floating point/decimal number
- then one whitespace
- then one or more NON-WHITESPACE characters

Do you want me to 

- change the validation rule to accept '-80 degree Celsius'? Like, require a number, followed by a space, followed by a non-space character, followed by 0 or more characters of any type?
- change the example (which comes from MIxS) to match the existing validation rule? Like '-80 C'?

**Comment by pvangay** [comment]
which one is more in line with MIxS? Or is the issue that they guidance does not match their example?

**Comment by mslarae13** [comment]
Note on this, string_serialization does not show in the submission portal. Should it?

**Comment by ssarrafan** [comment]
@mslarae13 who is your question above directed to so I can try to get you an answer?

**Comment by pkalita-lbl** [comment]
This is working now. Closing.
