### ISSUE TITLE
Typo in geographic location (latitude and longitude) pattern hint

### ISSUE THREAD

**Issue by pvangay** [microbiomedata/sheets_and_friends#139]
Currently is: (lat lon}
Should be: {lat lon}

(reported by a Champion)

**Comment by turbomam** [comment]
Where does`(lat lon}` appear?

**Comment by turbomam** [comment]
[modifications_long](https://docs.google.com/spreadsheets/d/1cMlPKgjZh-v21aMYCm9x1TxzE5BwGQptBQcvuaYAtC8/edit#gid=1241218612&range=50:50)

**Comment by pvangay** [comment]
![image](https://user-images.githubusercontent.com/7374085/175719162-6accc69b-c9d0-424b-85fe-15830fd05072.png)

I'm currently in the built environment template ([example project](https://data.microbiomedata.org/submission/4082fa29-9312-4c1c-af5a-072aec49ab0e/samples))

**Comment by mslarae13** [comment]
This is correct in the src schema files. @turbomam where is this error at? Can you fix it?

**Comment by mslarae13** [comment]
Backlog until pattern hint (generated from string_serialization) is re-established

**Comment by mslarae13** [comment]
Error occurs in sheets_and_friends

I've corrected this in my working version of the sheet. See here: https://docs.google.com/spreadsheets/d/1Qc5dTdo39mNeMrE-WwVSz6SpjL0SiQ8vFfMrBF97804/edit#gid=928747012&range=2:2

When code freeze and schema sync is complete this should be merged into the 'official' sheet.

**Comment by ssarrafan** [comment]
I'll move this to the next sprint to be merged in.  FYI @mslarae13

**Comment by ssarrafan** [comment]
@mslarae13 @turbomam was this merged? Can this issue be closed?

**Comment by mslarae13** [comment]
It wasn't merged. Waiting for the schema freeze to end
This should probably go into "in review"

**Comment by ssarrafan** [comment]
@pkalita-lbl @turbomam does this actually need to be reviewed by anyone still?  It's been sitting here for 2 weeks.

**Comment by pkalita-lbl** [comment]
This one is suffering from extreme issue rot. I don't really know what the whole history is, and I'm not quite sure why I got added to the assignees. But I verified underlying bug has been fixed (`{lat lon}` is there instead of `(lat lon}`) by inspecting the schema. However you can't see the fix in the interface because of https://github.com/microbiomedata/sheets_and_friends/issues/170.  Regardless I think it's time to close this one.
