### ISSUE TITLE
"air temperature" and "absolute air humidity" example help text fails on validation

### ISSUE THREAD

**Issue by pvangay** [microbiomedata/sheets_and_friends#140]
Using the built environment template, a Champion reported that several examples in the help text failed on validation:

- For "air temperature": "20 degree Celsius" is provided as an example but did not validate. "20 degree" did pass validation. 
- For "absolute air humidity": "9 gram per gram" is provided as an example but did not validate
 
Please update either the validation or example to be consistent.

**Comment by turbomam** [comment]
Currently, all columns whose range is MIxS `measurement value` aka NMDC `quantity value` don't allow spaces in the units portion. I can change that globally, but we should think about whether that would have any undesired consequences

**Comment by pvangay** [comment]
sounds like a good topic of discussion at the next metadata meeting? (to identify a path forward and discuss undesired consequences). @mslarae13 

I don't have a strong feeling either way - we just need to be consistent with what we provide as an example vs. what we validate against.

**Comment by ssarrafan** [comment]
@turbomam moving this to Sept but please let me know if you're not actively working on it for the next 2 weeks

**Comment by mslarae13** [comment]
I assume this is actually ' humidity_regm' in which case, both work now. However we might want to make (unless one exists) a ticket for "updating and improving guidance and examples in template"
