### ISSUE TITLE
Swap first two columns in our DataHarmonizer interfaces

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/sheets_and_friends#144]
As of 2022-07-29, the first two columns in our DataHarmonizer interfaces are:

1. `source_mat_id`, [which MIxS titles "source material identifiers"](https://docs.google.com/spreadsheets/d/1QDeeUcDqXes69Y2RjU2aWgOpCVWo5OVsBX9MKmMqi_o/edit#gid=750683809&range=1483:1483) (but we have re-titled "globally unique ID" in [sheets-for-nmdc-submission-schema](https://docs.google.com/spreadsheets/d/1cMlPKgjZh-v21aMYCm9x1TxzE5BwGQptBQcvuaYAtC8/edit#gid=1241218612&range=83:83))
2. `samp_name`, which MIxS titles "sample name". That title isn't modified in `sheets-for-nmdc-submission-schema`, but some other attributes might have been.

I believe @mslarae13 would like to swap those order on all NMDC DataHarmonizer interfaces. In that case, `samp_name` is the column that will stay frozen when a user scrolls to the right. @mslarae13, did you have some additional expectation of how that would effect the way the DataHarmonizer saves the data?

I don't have any objection to this reordering.

**Comment by mslarae13** [comment]
I don't. Fields all the same. Just want users to be able to see their human readable ID (samp_name) when they scroll right so they know what samples they're adding metadata for at each row.

**Comment by turbomam** [comment]
aha, [mixin_slots](https://docs.google.com/spreadsheets/d/1cMlPKgjZh-v21aMYCm9x1TxzE5BwGQptBQcvuaYAtC8/edit#gid=667012330)

we'll have to do it for each section that is modeled as a LinkML `mixin`.

**Comment by mcovalt** [comment]
> please also chime in, but I would think the best way to indicate that new templates are ready is to open a PR in nmdc-server where you've updated this commit hash to the new version: https://github.com/microbiomedata/nmdc-server/blob/main/web/yarn.lock#L9244

Yeah, that would be the way to go. There are likely ways this could be automated using GitHub tools, but that might be finicky to set up.

**Comment by jeffbaumes** [comment]
@mcovalt will attempt using this template locally with real data and ensure existing data loads properly with the column swap before deploying this change.

**Comment by mcovalt** [comment]
Testing this locally revealed the need to also swap existing columns in PostgreSQL. I'll follow up on Monday with the progress of that migration.

**Comment by turbomam** [comment]
Thanks @mcovalt !

I think I'm hearing "dependence on column ordering during data transport"

Will we be able to avoid that in the future?

**Comment by mcovalt** [comment]
The JSON we store represents the submission metadata as a list-of-lists. The second lists defines the mapping of subsequent lists. It's a bit like how a CSV header line defines the field name for subsequent lines.

In the frontend we must be loading the lists without regard to the mapping list. Now that I'm talking about this out-loud, a better solution wouldn't have involved a data migration, but instead would be to fix this frontend behavior.
