### ISSUE TITLE
Allow users to freeze "sample name" column

### ISSUE THREAD

**Issue by pvangay** [microbiomedata/sheets_and_friends#146]
ESS attendees noted that when scrolling to columns to the far right of the submission interface, they would like to be able to see the "sample name" of each row. Currently, only the globally unique ID column is frozen, and this value is not as informative (usually generated at the time of metadata entry - most researchers identify their samples with the values in "sample name").

A few options:
- Freeze both "globally unique ID" and "sample name"
- Freeze "sample name" only
- Allow user to freeze any column of their choice (I realize this one may be difficult to implement and not feasible)

**Comment by turbomam** [comment]
Per @mslarae13, I switched the first two columns so that "globally unique ID" appears leftmost, then "sample name"

There is also an [issue open at DataHarmonizer](https://github.com/cidgoh/DataHarmonizer/issues/334) for freezing more than the one leftmost column can be frozen

**Comment by pvangay** [comment]
oh sorry!! let me close this one. I'll do a more thorough check first before creating new issues.

**Comment by turbomam** [comment]
Demo website: https://microbiomedata.github.io/sheets_and_friends/main.html?template=nmdc_submission_schema/soil_emsl_jgi_mg

**Comment by turbomam** [comment]
> oh sorry!! let me close this one. I'll do a more thorough check first before creating new issues.

No biggie.
