### ISSUE TITLE
Updated source_mat_id on submission portal

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/sheets_and_friends#157]
I've updated the description & guidance for source_mat_id.

See: https://docs.google.com/spreadsheets/d/1cMlPKgjZh-v21aMYCm9x1TxzE5BwGQptBQcvuaYAtC8/edit#gid=1241218612 
Row 77, 78, 79

In accordance with https://github.com/microbiomedata/nmdc-schema/issues/372 feedback.

Updates need added to data harmonizer and the submission portal.

**Comment by mslarae13** [comment]
Adding to SubPort squad. I think this is done? Need to confirm.

**Comment by turbomam** [comment]
This issue mentions the following issue with closed status:
- https://github.com/microbiomedata/nmdc-schema/issues/372

But neither this issue or the linked issue mention a PR. If there was a merged PR, that's usually strong grounds to close all linked issues. But we'll have do some manual double checking in this case.

**Comment by mslarae13** [comment]
Did a quick check! Looks like I edited the linked google sheet https://docs.google.com/spreadsheets/d/1cMlPKgjZh-v21aMYCm9x1TxzE5BwGQptBQcvuaYAtC8/edit?usp=sharing 

But made no changes to the schema. I can go ahead and make a branch for this and update it in the schema.

**Comment by mslarae13** [comment]
https://github.com/microbiomedata/nmdc-schema/pull/683
