### ISSUE TITLE
`gen-python` errors out on submission schema

### ISSUE THREAD

**Issue by sujaypatil96** [microbiomedata/sheets_and_friends#165]
Running `gen-python` on the submission schema YAML in this repo: https://github.com/microbiomedata/sheets_and_friends/blob/main/artifacts/nmdc_submission_schema.yaml gives us an error:

```
$ gen-python schema/nmdc_submission_schema.yaml > schema/nmdc_submission_schema.py

WARNING:Namespaces:mixs namespace is already mapped to https://w3id.org/mixs/terms/ - Mapping to https://w3id.org/mixs/ ignored
IndexError: string index out of range
```

**Comment by pkalita-lbl** [comment]
Submission schema is now here https://github.com/microbiomedata/submission-schema and includes Python artifacts. Closing.
