### ISSUE TITLE
modifications_long tab in sheets_and_friends configuration sheet not being applied to multi-view DH

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/sheets_and_friends#171]
The modifications_long tab in sheets_and_friends configurations like [sheets-for-nmdc-submission-schema_MLS](https://docs.google.com/spreadsheets/d/1Qc5dTdo39mNeMrE-WwVSz6SpjL0SiQ8vFfMrBF97804/edit#gid=1241218612) define modifications that should be made to MIxS terms before they are included in the [submission schema](https://github.com/microbiomedata/sheets_and_friends/blob/main/artifacts/nmdc_submission_schema.yaml), or any DataHarmonizer built from it.

The modification are applied by the `artifacts/nmdc_submission_schema.yaml` rule in the Makefile, which calls the `modifications_and_validation` script.

It appears that modifications are not being applied anymore. We're not sure when that started. Note that sheets_and_friends can apply different modifications on a class-by-class basis. _In fact, the modifications were applied by specifying a `slot_usage` for each slot in each class, which lead to the enormous file sizes in the past._

For example, modification_long says that `samp_store_temp`'s `description` should be changed from the MIxS specified value of "Temperature at which sample was stored, e.g. -80 degree Celsius" to the [modified value of 'Temperature at which the sample was stored (degrees are assumed)'](https://docs.google.com/spreadsheets/d/1Qc5dTdo39mNeMrE-WwVSz6SpjL0SiQ8vFfMrBF97804/edit#gid=1241218612&range=G208).

This was successful in [commit d93ce72be9bf96af6316e01dfdd947cb2983d3c0](https://raw.githubusercontent.com/microbiomedata/sheets_and_friends/d93ce72be9bf96af6316e01dfdd947cb2983d3c0/artifacts/nmdc_submission_schema.yaml)

Recently @mslarae13 added modifications for more terms like `fire`, be we don't have as much history about whether that was ever applied sucessfully.

Criteria for completion
- [ ] Fix the sheets_and_friends workflow so that DataHarmonizers intended for the Submission Portal include all modifications specified in the modifications_long Google sheet tab. This should include multi-view DH build.
- [ ] Test in dev
- [ ] Push updates to prod

**Comment by mslarae13** [comment]
We will discuss on 02/14 at SubPort squad meeting
@pkalita-lbl , @turbomam

**Comment by mslarae13** [comment]
When you make changes to sheets-and-friends the main branch needs the 
Feb 3rd was the last time artifacts were made. 

Need to make an SOP or ?? for the protocol for updating the sheets_and_friends
- Make a copy of the "main" sheets-and-friends

For GSP: When schema freeze is over, merge / update to Montana's sheets_and_friends file, remake the make file, and push these slot updates to the submission portal
-  import_slots_regardless tab in sheets-for-nmdc-submission-schema in column 'source file or URL' should point to a tag, not main

NOT for GSP: Develop a better way of tracking, merging, and resolving the schema updates that happen in sheets-and-friends for the Submission Portal

**Comment by pkalita-lbl** [comment]
This issue refers to issues around the shared Google sheet. That is no longer being used in favor of TSV files checked into https://github.com/microbiomedata/submission-schema. I think it's safe to close this one.
