### ISSUE TITLE
standardize multiple examples on one slot

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/sheets_and_friends#42]
- with semicolon: 'tree; chair'
- with "or": 'tree or chair'
- with vertical pipe character: 'tree|chair'
- as two individual examples:
  - tree
  - chair

**Comment by turbomam** [comment]
going with semicolon for now

**Comment by mslarae13** [comment]
@turbomam what is left to do here?

**Comment by mslarae13** [comment]
Pipe | used to separate multiple values ... ; used to separate the individual tokens within a compound value

Need to define multi-valued slot vs compound value and compound value pattern + multi-valued = true

agrochem_addition example doesn't validate. Need to revisit this. 
- need 2 valid examples
- Mark will check this slot as a test case

**Comment by mslarae13** [comment]
https://github.com/microbiomedata/issues/issues/78

**Comment by mslarae13** [comment]
@turbomam  how is this coming? Will you be able to finish by the end of the sprint?

**Comment by ssarrafan** [comment]
This appears to be active so I will move to the next sprint. @mslarae13 thank you for trying to get an update on this.

**Comment by pkalita-lbl** [comment]
DH already uses the multivalued nature of the `examples` metamodel slot to show different examples as separate bullets. We need to write our examples to take advantage of that. In some cases that may mean overriding the MIxS examples. 

Some good slots to consider:
* collection time
* extreme_unusual_properties/heavy metals
* agrochem_addition

**Comment by pkalita-lbl** [comment]
End of sprint update: this one came in late, but I intend to work on it in the next sprint.

**Comment by turbomam** [comment]
Great. I think there are still non-standardized multiple examples that come straight from GSC. I'll work on those.
