### ISSUE TITLE
Could we drop the parenthetical portion of the cur_land_use permissible values?

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/sheets_and_friends#60]
I have code that ignores the parenthetical portion when mapping to EnvO terms, but even _displaying_ them in the DH pulldowns is awkward

- badlands
- cities
- conifers (e.g. pine,spruce,fir,cypress)
- crop trees (nuts,fruit,christmas trees,nursery trees)
- farmstead
- gravel
- hardwoods (e.g. oak,hickory,elm,aspen)
- hayland
- horticultural plants (e.g. tulips)
- industrial areas
- intermixed hardwood and conifers
- marshlands (grass,sedges,rushes)
- meadows (grasses,alfalfa,fescue,bromegrass,timothy)
- mines/quarries
- mudflats
- oil waste areas
- pastureland (grasslands used for livestock grazing)
- permanent snow or ice
- rainforest (evergreen forest receiving >406 cm annual rainfall)
- rangeland
- roads/railroads
- rock
- row crops
- saline seeps
- salt flats
- sand
- shrub crops (blueberries,nursery ornamentals,filberts)
- shrub land (e.g. mesquite,sage-brush,creosote bush,shrub oak,eucalyptus)
- small grains
- successional shrub land (tree saplings,hazels,sumacs,chokecherry,shrub dogwoods,blackberries)
- swamp (permanent or semi-permanent water body dominated by woody plants)
- tropical (e.g. mangrove,palms)
- tundra (mosses,lichens)
- vegetable crops
- vine crops (grapes)

**Comment by turbomam** [comment]
2023-05-18: yes, remove the parenthetical portions form the PV texts

put the parenthetical examples as annotations on the permissible values

**Comment by turbomam** [comment]
I am going to do this manually now and make an issue for a better approach in the future, either

**Comment by turbomam** [comment]
The PV are not asserted in schemasheets/tsv_in/enums.tsv

They are inherited via

```make
local/with_shuttles.yaml: local/from_schemasheets.yaml \
sheets_and_friends/tsv_in/import_slots_regardless.tsv
		$(RUN) do_shuttle \
			--config_tsv  $(word 2,$^) \
			--recipient_model $(word 1,$^) \
			--yaml_output $@.raw
```

**Comment by ssarrafan** [comment]
@turbomam does this mean this issue is done (manually) and can be closed?

**Comment by turbomam** [comment]
Re https://github.com/microbiomedata/sheets_and_friends/issues/60#issuecomment-1555288503

No, still in progress

**Comment by ssarrafan** [comment]
Based on recent comments assuming this is active, moving to new sprint. @turbomam

**Comment by ssarrafan** [comment]
This GH issue is over 1 year old.  @turbomam does this question still need to be answered?  What's the goal for this issue?

**Comment by mslarae13** [comment]
@turbomam  is the only thing left to go here to get this into prod on the submission portal?

@pkalita-lbl  ?

**Comment by pkalita-lbl** [comment]
The updated schema is on dev. Is there an expectation that we modify existing submissions in the portal to match the new values? So, for example, if an in-progress submission uses "crop trees (nuts,fruit,christmas trees,nursery trees)", change it to "crop trees" for them?

**Comment by mslarae13** [comment]
@pkalita-lbl good question! Will keeping it as "crop trees (nuts,fruit,christmas trees,nursery trees)" validate? cause issues downstream / with database transforming and sharing?

**Comment by pkalita-lbl** [comment]
No, without writing a migration once the new version of the submission schema is brought into the portal old submissions with "crop trees (nuts,fruit,christmas trees,nursery trees)" in them already will not validate anymore. It could potentially confuse the submission-portal-to-Mongo pipeline, but we wouldn't run that on a submission that doesn't validate in the first place.

Since the migration logic is quite straightforward (replace these old values with these new values) in this case I'll go ahead and include it when I bring the latest submission schema into the portal.

**Comment by pkalita-lbl** [comment]
This is moving through the system as part of https://github.com/microbiomedata/nmdc-server/pull/992

**Comment by ssarrafan** [comment]
Closing this based on @pkalita-lbl last comment.  
Backlog cleanup 12-2023
