### ISSUE TITLE
GOLD path terms should be required

### ISSUE THREAD

**Issue by pvangay** [microbiomedata/sheets_and_friends#65]
These should be required and highlighted yellow. Confirmed this persists on https://microbiomedata.github.io/sheets_and_friends/main.html as well. 
![image](https://user-images.githubusercontent.com/7374085/155234595-383adddd-9e14-4104-b69c-2b7e48d83218.png)

**Comment by turbomam** [comment]
migrated

**Comment by turbomam** [comment]
Made modifications in Google Sheet like https://docs.google.com/spreadsheets/d/1RACmVPhqpfm2ELm152CzmiEy2sDmULmbN9G0qXK8NDs/edit#gid=1241218612&range=379:379

then regenerated DH interface with `make all; git add *; git commit -m "message etc etc"; git push`

should be visible at https://microbiomedata.github.io/sheets_and_friends/main.html soon
