### ISSUE TITLE
increase Google Sheets API reads per minute per user quota etc

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/sheets_and_friends#87]
May need to do this through LBL, or tie existing project to LBL first

**Comment by turbomam** [comment]
@turbomam  will push code to include a sleep step between cogs operations

**Comment by turbomam** [comment]
see #61

**Comment by ssarrafan** [comment]
@turbomam I checked with Ed who works for JGI and used to work at Google but he is not familiar with the API. Sorry! I will move this to July.

**Comment by turbomam** [comment]
@sujaypatil96 @mcovalt this hasn't been a problem for me recently. I was thinking about decreasing or eliminating the sleep step

@sujaypatil96 were you granted an increase to this quota? Did you apply it? How could one of see that to better understand what you did?

**Comment by sujaypatil96** [comment]
@turbomam so we requested for an increase of the requests per min per user quota from the same Google account that was used to create the client secret JSON file. If we look through the inbox for that account, we should see an email response from Google Cloud support regarding our request.

**Comment by turbomam** [comment]
Sure Mark, I'll look into this issue. Will ping you if I have any questions
about the account.

**Comment by ssarrafan** [comment]
Based on Sujay's note I will close this issue but let me know if it should be re-opened.

**Comment by turbomam** [comment]
I think that was a service account, so I don't know how to check the email.
Can you look into that please @Sujay Patil ***@***.***> ?
